Stripe
UoaWDCC/aspa-portal-v2 pull request #70
Opened 2023-07-20 00:48 UTC by ahua352

2023-07-25 23:29 UTC, JC4github commented on packages/backend/src/event/event-model.ts
> + * @property {boolean} paymentStatus - whether the user has already paid for the event
I believe we decided to change paymentStatus to isPaid

2023-07-25 23:34 UTC, JC4github commented on packages/backend/src/user/user-model.ts
> + * @property {boolean} paymentStatus - whether the user has already paid for the event
For consistency, paymentStatus should be updated to isPaid

2023-07-25 23:36 UTC, JC4github commented on packages/backend/src/user/user-model.ts
> +  paymentStatus: boolean;
Update paymentStatus to isPaid

2023-07-25 23:37 UTC, JC4github commented on packages/backend/src/user/user-model.ts
> +      paymentStatus: Boolean,
Update paymentStatus to isPaid

2023-07-25 23:39 UTC, JC4github requested changes
Just need to refactor paymentStatus to isPiad for consistency, but the rest of the code looks good to me.

2023-07-26 07:59 UTC, ahua352 reviewed
I've now renamed paymentStatus to isPaid and merged the webhook branch

2023-07-27 00:03 UTC, JC4github approved these changes
Looks great!

2023-07-27 00:03 UTC, merged